core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

miFamiliaNativa/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'miFamiliaNativa'

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter your username',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter your username',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Enter your email address',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

core/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm


def index(request):
    return render(request, 'core/index.html')


def contact(request):
    return render(request, 'core/contact.html')


def about(request):
    return render(request, 'core/about.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()

    form = SignupForm()
    return render(request, 'core/signup.html', {
        'form': form,
    })

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %}About{% endblock %}
{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h1 class="text-4xl">Sobre nosotros</h1>
        <div class="flex grid grid-cols-2 gap-3 text-center">
            <div class="p-6 bg-white rounded-b-xl">
                <h2 class="bold text-3xl">Miquel Puig</h2>
                <div>
                    <img src="#" class="rounded-t-xl">
                </div>
                <p class="text-gray-500 text-xl">
                    Nacido en Barcelona (España) en 1969, está especializado desde hace casi 20 años en organizar
                    servicios educativos para niños y jóvenes dentro del modelo educativo no formal (MENOF), primero con
                    su propia empresa SCHOOL HOUSE y después como directivo en la empresa INTERNATIONAL HOUSE, en el
                    sector de la enseñanza de idiomas.<br><br>
                    Ha creado y coordinado entre los años 2008 y 2020 el Concurso de Inglés Interescolar de Catalunya y
                    Baleares (THE FONIX) en colaboración con el Departament d' Ensenyament de la Generalitat de
                    Catalunya y del Govern Balear, con decenas de miles de concursantes. En 2016 funda la Asociación de
                    Escuelas de Español como Lengua Extranjera en las Islas Baleares (Fedele Baleares), y en 2017 crea
                    la Asociación Cultural y de Amistad entre Catalunya y Escocia (SCOTCAT). Ha organizado también
                    diversos eventos y actividades para niños, jóvenes y docentes en el ámbito de la formación y el
                    ocio.
                </p>
            </div>
            <div class="p-6 bg-white rounded-b-xl">
                <h2 class="bold text-3xl">Luigi Bugalla</h2>
                <div>
                    <img src="#" class="rounded-t-xl">
                </div>
                <p class="text-gray-500 text-xl">Nacido en Turín (Italia) en 1964, es políglota y language consultant
                    especializado en el aprendizaje práctico de idiomas. Hasta la fecha ha formado a más de 800 alumnos.
                    Emprendedor vocacional desde los 18 años y focalizado en el área de recursos humanos y comercial, ha
                    colaborado como socio estratégico en más de 15 proyectos en los ámbitos educativo y cultural.
                    En 2014 funda 20 COFFES SPEAKING GROUPS, un servicio que ofrece la posibilidad de aprender,
                    refrescar o mejorar el idioma conversando en grupos reducidos en cafeterías de Barcelona. Más
                    recientemente ha ampliado su oferta al mundo online con un componente añadido de intercambio
                    cultural. Su experiencia abarca la enseñanza de español, inglés, francés, italiano, ruso y chino.
                    Desde 2001 es directivo de la Asociación de Consumidores de Medios Audiovisuales de Cataluña (TAC).
                    Recientemente ha sido nombrado Secretario de la Asociación Pro Beatificación de Antoni Gaudí.</p>
            </div>

        </div>
    </div>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | Mi Familia Nativa</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">Inicio</a>
        <!-- logo -->

        <div class="space-x-6">
            <a href="{% url 'core:index' %}" class="text-lg font-semibold hover:text-gray-500">Inicio</a>
            <a href="{% url 'core:about' %}" class="text-lg font-semibold hover:text-gray-500">Nosotros</a>

            {% if request.user.is_authenticated %}
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
            {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
            {% endif %}
        </div>
    </nav>
    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">Lorem ipsum blah blah blah lorem ipsum blah blah blah</p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

            <ul class="space-y-2">
                <li><a href="{% url 'core:about' %}" class="text-lg text-teal-500 hover:text-teal-700">Nosotros</a></li>
                <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contacto</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of use</a></li>
            </ul>
        </div>
    </footer>

</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}
{% block content %}
    <h1>Gracias por conectar con el equipo de Mi Familia Nativa</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Mi Familia Nativa{% endblock %}
{% block content %}
    <h1>{{ title }}</h1>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Qué es Mi Familia Nativa?</h2>
        <p>El buscador de familias nativas para inmersiones lingüísticas cerca de casa</p>

    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Login</h1>

        <form method="post" action=".">
            {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Sign up</h1>

        <form method="post" action=".">
            {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{ form.email }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password1 }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Repeat password</label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock %}